import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { defaultConfig } from "../../src/config/defaultConfig.js";
import { generateFromHar } from "../../src/generator/orchestrator.js";

const tmpDirs: string[] = [];

const generatedBanner =
  "// GENERATED by har-api-tests — do not edit by hand.\n// Regenerate with: npm run generate -- --har <your capture file or folder>\n";

afterEach(async () => {
  await Promise.all(
    tmpDirs
      .splice(0)
      .map((dir) => fs.rm(dir, { recursive: true, force: true })),
  );
});

describe("multi-host generation", () => {
  it("filters third-party/beacon hosts and bakes per-host routing into the support file", async () => {
    const root = await fs.mkdtemp(
      path.join(os.tmpdir(), "har-api-tests-multi-"),
    );
    tmpDirs.push(root);
    const harPath = path.join(root, "multi.har");
    const outDir = path.join(root, "generated");
    await fs.writeFile(
      harPath,
      JSON.stringify(multiHostHar(), null, 2),
      "utf8",
    );

    const summary = await generateFromHar(
      {
        harInputs: [harPath],
        outDir,
        include: [],
        exclude: [],
        ignoredDomains: [],
        firstPartyDomains: [],
        methods: [],
        statuses: [],
        generationModes: ["smoke", "extended"],
        inferenceLevel: "balanced",
        inferredRunMode: "mixed",
        negativeStatusPolicy: "family",
        mutationPolicy: "guarded",
        ai: false,
        dryRun: false,
      },
      defaultConfig,
    );

    const dirs = await fs.readdir(outDir);
    const support = await fs.readFile(
      path.join(outDir, "support", "apiTestUtils.ts"),
      "utf8",
    );
    const usersSpec = await fs.readFile(
      path.join(outDir, "api-acme-test", "v1-users.spec.ts"),
      "utf8",
    );
    const manifest = JSON.parse(
      await fs.readFile(path.join(outDir, "run-manifest.json"), "utf8"),
    ) as {
      sources: { harFiles: string[] };
    };

    // Intercom (tracking) + beacon path is dropped; both first-party hosts are kept.
    expect(dirs).not.toContain("api-iam-eu-intercom-io");
    expect(dirs).toContain("api-acme-test");
    expect(dirs).toContain("cdn-other-test");

    // Auth is disabled by default. With no captured placeholders there are no required variables,
    // so generation must not invent credential requirements or a preflight spec.
    expect(dirs).not.toContain("00-preflight.spec.ts");

    expect(usersSpec.startsWith(generatedBanner)).toBe(true);
    expect(support.startsWith(generatedBanner)).toBe(true);

    // @mutating marks state-changing cases only; guarded POST runs automatically while the
    // inferred contract enters machine calibration.
    expect(usersSpec).toContain(
      "test('smoke: GET /v1/users returns 200 @smoke @profile'",
    );
    expect(usersSpec).toContain(
      "test('smoke: POST /v1/users returns 201 @smoke @profile @mutating'",
    );
    expect(usersSpec).toContain(
      "calibrationTest('negative: POST /v1/users rejects missing name @extended @profile @mutating @calibrate'",
    );
    expect(usersSpec).not.toContain("test.fixme");
    expect(usersSpec).not.toContain("inferredTest");

    // Manifest sources stay portable across machines/CI checkouts.
    expect(manifest.sources.harFiles).toEqual([
      path.relative(process.cwd(), harPath),
    ]);

    // The support file bakes the observed hosts and picks the most frequent as primary.
    expect(support).toContain('"api.acme.test"');
    expect(support).toContain('"cdn.other.test"');
    expect(support).toContain("BASE_URL_' + envHostSlug(host)");
    expect(support).toContain('const PRIMARY_HOST = "api.acme.test"');

    // 3 first-party endpoints -> 3 smoke tests; intercom beacon excluded.
    expect(summary.filteredEntries).toBe(3);
  });
});

function multiHostHar(): unknown {
  const jsonResponse = (body: unknown, status = 200) => ({
    status,
    headers: [{ name: "Content-Type", value: "application/json" }],
    content: { mimeType: "application/json", text: JSON.stringify(body) },
  });

  return {
    log: {
      version: "1.2",
      entries: [
        {
          time: 20,
          request: {
            method: "GET",
            url: "https://api.acme.test/v1/users?limit=1",
            headers: [],
            queryString: [{ name: "limit", value: "1" }],
          },
          response: jsonResponse({ users: [], total: 0 }),
        },
        {
          time: 30,
          request: {
            method: "POST",
            url: "https://api.acme.test/v1/users",
            headers: [{ name: "Content-Type", value: "application/json" }],
            postData: {
              mimeType: "application/json",
              text: JSON.stringify({ name: "Grace" }),
            },
          },
          response: jsonResponse({ id: "1", name: "Grace" }, 201),
        },
        {
          time: 15,
          request: {
            method: "GET",
            url: "https://cdn.other.test/v1/widgets",
            headers: [],
          },
          response: jsonResponse({ widgets: [] }),
        },
        {
          time: 10,
          request: {
            method: "POST",
            url: "https://api-iam.eu.intercom.io/messenger/web/ping",
            headers: [
              {
                name: "Content-Type",
                value: "application/x-www-form-urlencoded",
              },
            ],
            postData: {
              mimeType: "application/x-www-form-urlencoded",
              text: "app_id=abc",
            },
          },
          response: jsonResponse({ ok: true }),
        },
      ],
    },
  };
}
