import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { defaultConfig } from "../../src/config/defaultConfig.js";
import {
  buildPlaywrightAuthSetupFile,
  buildPlaywrightSupportFile,
} from "../../src/generator/playwrightSupport.js";
import { planGeneratedTests } from "../../src/generator/testPlanner.js";
import { writeGeneratedTests } from "../../src/generator/testGenerator.js";
import type { NormalizedHarEntry } from "../../src/types/har.js";

const generatedBanner =
  "// GENERATED by har-api-tests — do not edit by hand.\n// Regenerate with: npm run generate -- --har <your capture file or folder>\n";

describe("v2 generator", () => {
  it("writes endpoint-centered specs with guarded smoke and calibration-aware inferred tests", async () => {
    const outDir = await fs.mkdtemp(
      path.join(os.tmpdir(), "har-api-tests-v2-"),
    );
    const plan = planGeneratedTests([loginEntry()], defaultConfig, {
      mutationPolicy: "guarded",
    });

    const generatedFiles = await writeGeneratedTests(
      plan,
      outDir,
      defaultConfig,
    );

    const specPath = path.join(
      outDir,
      "api-example-test",
      "auth-main-login.spec.ts",
    );
    const spec = await fs.readFile(specPath, "utf8");
    const support = await fs.readFile(
      path.join(outDir, "support", "apiTestUtils.ts"),
      "utf8",
    );
    const authSetup = await fs.readFile(
      path.join(outDir, "support", "authSetup.ts"),
      "utf8",
    );
    const fixtureFiles = await fs.readdir(path.join(outDir, "fixtures"));
    const schemaFiles = await fs.readdir(path.join(outDir, "schemas"));
    const runManifest = JSON.parse(
      await fs.readFile(path.join(outDir, "run-manifest.json"), "utf8"),
    ) as {
      summary: {
        schemaCount: number;
        categories: Record<string, number>;
        executions: Record<"active" | "calibrate" | "skip", number>;
      };
      environment: { required: string[]; optional: string[] };
    };
    const envExample = await fs.readFile(
      path.join(outDir, ".env.generated.example"),
      "utf8",
    );

    expect(spec.startsWith(generatedBanner)).toBe(true);
    expect(support.startsWith(generatedBanner)).toBe(true);
    expect(authSetup.startsWith(generatedBanner)).toBe(true);

    expect(spec).toContain(
      "test('smoke: POST /auth/main/login returns 200 @smoke @auth @mutating'",
    );
    // Pending inferred cases are quarantined in normal runs and activated by the machine-operated
    // calibration lane, with no human-review execution state.
    expect(spec).toContain(
      "calibrationTest('negative: POST /auth/main/login rejects missing password @extended @auth @mutating @calibrate'",
    );
    expect(spec).toContain(
      "calibrationTest('security: POST /auth/main/login rejects missing authorization @extended @auth @mutating @calibrate'",
    );
    expect(spec).toMatch(
      /import \{[^}]*\bcalibrationTest\b[^}]*\} from '\.\.\/support\/apiTestUtils\.js';/,
    );
    expect(spec).not.toContain("test.fixme");
    expect(spec).not.toContain("inferredTest");
    expect(spec).not.toContain("boundary:");
    expect(spec).toContain("sendApiRequest({");
    expect(spec).toContain("suppressGeneratedAuth: true");

    const preflightPath = path.join(outDir, "00-preflight.spec.ts");
    const preflight = await fs.readFile(preflightPath, "utf8");
    expect(generatedFiles).toContain(preflightPath);
    expect(preflight.startsWith(generatedBanner)).toBe(true);
    expect(preflight).toContain(
      "import { expect, test } from '@playwright/test';",
    );
    expect(preflight).toContain(
      "import { resolveGeneratedEnvValue } from './support/apiTestUtils.js';",
    );
    expect(preflight).toContain(
      "const requiredEnvNames = ['CSRF_TOKEN', 'TEST_EMAIL', 'TEST_PASSWORD'];",
    );
    expect(preflight).toContain(
      "test('preflight: required environment variables are resolvable @smoke @preflight'",
    );
    expect(authSetup).toContain("replaceGeneratedEnvValues(generatedValues)");
    expect(authSetup).toContain("clearGeneratedEnvValues()");
    expect(authSetup).toContain("AUTH_IGNORE_HTTPS_ERRORS', 'false'");
    expect(authSetup).not.toContain("const bodyPreview");
    expect(authSetup).not.toContain("' Body: '");
    expect(authSetup).toContain(
      "AUTH_LOGIN_URL is required when AUTH_STRATEGY=http-login",
    );
    expect(authSetup).toContain(
      "const bodyTemplate = requiredEnvValue('AUTH_LOGIN_BODY');",
    );
    expect(authSetup).not.toContain("stageautomation.heartpace.dev");
    expect(authSetup).not.toContain("defaultLoginData");
    expect(spec).toContain(
      'assertStatusCode(response.status(), {"kind":"family","family":"4xx"}',
    );
    expect(spec).toContain("validateSchema(responseBody, schema");
    expect(
      fixtureFiles.some((file) => file.includes("missing-field-password")),
    ).toBe(true);
    expect(schemaFiles).toContain(
      "post-api-example-test-auth-main-login.response.schema.json",
    );
    expect(runManifest.summary.schemaCount).toBe(1);
    expect(runManifest.summary.categories.negative).toBeGreaterThan(0);
    expect(runManifest.summary.executions).toEqual({
      active: 1,
      calibrate: 8,
      skip: 0,
    });
    expect(runManifest.environment.required).toEqual(
      expect.arrayContaining(["CSRF_TOKEN", "TEST_EMAIL", "TEST_PASSWORD"]),
    );
    expect(runManifest.environment.optional).not.toContain("CSRF_TOKEN");
    expect(runManifest.environment.optional).toEqual(
      expect.arrayContaining([
        "API_AUTHORIZATION",
        "AUTH_LOGIN_BODY",
        "AUTH_LOGIN_URL",
        "AUTH_STRATEGY",
        "BASE_URL",
        "TRUSTED_API_ORIGINS",
      ]),
    );
    expect(runManifest.environment.optional).not.toContain(
      "ALLOW_LIVE_API_TESTS",
    );
    expect(runManifest.environment.optional).not.toContain(
      "ALLOW_MUTATING_API_TESTS",
    );
    expect(runManifest.environment.optional).not.toContain("AUTH_LOGIN_PATH");
    expect(envExample).toContain("TEST_PASSWORD=");
    expect(envExample).toContain("BASE_URL=");
    expect(envExample).not.toContain("AUTH_SETUP_ENABLED");
    expect(envExample).toContain("AUTH_STRATEGY=none");
  });

  it("automatically skips unsafe destructive smokes and lenient inferred expectations", async () => {
    const outDir = await fs.mkdtemp(
      path.join(os.tmpdir(), "har-api-tests-v2-delete-"),
    );
    const plan = planGeneratedTests([deleteEntry()], defaultConfig, {
      mutationPolicy: "guarded",
      calibrationOverrides: [
        {
          title: "negative: DELETE /items/{id} rejects invalid path parameter",
          observedStatus: 204,
        },
      ],
    });

    await writeGeneratedTests(plan, outDir, defaultConfig);

    const spec = await fs.readFile(
      path.join(outDir, "api-example-test", "items-id.spec.ts"),
      "utf8",
    );

    expect(spec.startsWith(generatedBanner)).toBe(true);
    expect(spec).toContain(
      "test.skip('smoke: DELETE /items/{id} returns 204 @smoke @items @mutating'",
    );
    expect(spec).not.toContain("@smoke @items @mutating @calibrate");
    expect(spec).toContain(
      "test.skip('negative: DELETE /items/{id} rejects invalid path parameter @extended @items @mutating'",
    );
    expect(spec).toContain("| mutationRisk: guarded | calibration: lenient");
    expect(spec).toContain("| mutationRisk: unsafe\n");
    expect(spec).not.toContain("test.fixme");
    expect(spec).not.toContain("inferredTest");
    expect(spec).not.toContain("calibrationTest");
  });

  it("imports loadJsonFromTestFile for schema assertions even when no fixture exists", async () => {
    const outDir = await fs.mkdtemp(
      path.join(os.tmpdir(), "har-api-tests-v2-get-"),
    );
    // A plain GET with a JSON response body: schema assertion without any request-body fixture.
    const plan = planGeneratedTests([getOrdersEntry()], defaultConfig);

    await writeGeneratedTests(plan, outDir, defaultConfig);

    const spec = await fs.readFile(
      path.join(outDir, "api-example-test", "v1-orders.spec.ts"),
      "utf8",
    );
    const replayManifest = JSON.parse(
      await fs.readFile(path.join(outDir, "replay-manifest.json"), "utf8"),
    ) as {
      routes: Array<Record<string, unknown>>;
    };
    const importBlock = spec.slice(0, spec.indexOf("test.describe"));

    expect(spec).toContain("loadJsonFromTestFile<object>(testInfo.file");
    expect(importBlock).toContain("loadJsonFromTestFile");
    // No fixture in this spec, so the payload resolver stays unimported.
    expect(importBlock).not.toContain("resolvePayload");
    // Every referenced support identifier must be imported.
    for (const identifier of [
      "assertResponseTime",
      "assertStatusCode",
      "sendApiRequest",
      "readJsonResponse",
      "validateSchema",
      "loadJsonFromTestFile",
    ]) {
      expect(
        spec.includes(identifier) ? importBlock.includes(identifier) : true,
      ).toBe(true);
    }
    expect(replayManifest.routes).toHaveLength(1);
    expect(replayManifest.routes[0]).toMatchObject({
      method: "GET",
      hostname: "api.example.test",
      pathPattern: "/v1/orders",
      pathWithQuery: "/v1/orders",
      requestHeaders: {},
      status: 200,
      contentType: "application/json",
      responseBody: {
        orders: [{ id: "order-1", total: 12 }],
        total: 1,
      },
    });
  });

  it("emits exact-origin, credential, calibration, and auth-strategy support code without human gates", () => {
    const support = buildPlaywrightSupportFile();
    const authSetup = buildPlaywrightAuthSetupFile();

    expect(support).toContain(
      "for generated test placeholder ${' + envName + '}",
    );
    expect(support).not.toContain("\\ + envName + ");
    expect(support).toContain("envName === 'CACHE_BUSTER'");
    expect(support).toContain("sendApiRequest");
    expect(support).toContain("assertAllowedTarget");
    expect(support).toContain("calibrationTest");
    expect(support).not.toContain("inferredTest");
    expect(support).not.toContain("test.fixme");
    expect(support).not.toContain("assertMutationAllowed");
    expect(support).not.toContain("ALLOW_LIVE_API_TESTS");
    expect(support).not.toContain("ALLOW_MUTATING_API_TESTS");
    expect(support).toContain("AUTH_BEARER_ORIGINS");
    expect(support).toContain("AUTH_COOKIE_ORIGINS");
    expect(support).toContain("shouldAttachBearer");
    expect(support).not.toContain("DEFAULT_BEARER_HOSTS");
    expect(support).not.toContain("AUTH_BEARER_HOSTS");
    expect(authSetup).toContain("globalSetup");
    expect(authSetup).toContain("envValue('AUTH_STRATEGY', 'none')");
    expect(authSetup).not.toContain("AUTH_SETUP_ENABLED");
    expect(authSetup).toContain("clearGeneratedAuthSnapshot()");
    expect(authSetup).toContain(
      "AUTH_LOGIN_URL is required when AUTH_STRATEGY=http-login",
    );
    expect(authSetup).toContain(
      "const bodyTemplate = requiredEnvValue('AUTH_LOGIN_BODY');",
    );
    expect(authSetup).not.toContain("stageautomation.heartpace.dev");
    expect(authSetup).not.toContain("AUTH_LOGIN_PATH', '/auth/main/login'");
    expect(authSetup).not.toContain("TEST_EMAIL");
    expect(authSetup).not.toContain("TEST_PASSWORD");
    expect(authSetup).toContain("replaceGeneratedEnvValues(generatedValues)");
    expect(authSetup).toContain(
      "generatedValues.API_AUTHORIZATION = 'Bearer ' + authToken",
    );
  });
});

function getOrdersEntry(): NormalizedHarEntry {
  return {
    id: "get-api-example-test-v1-orders",
    sourceFile: "orders.har",
    entryIndex: 0,
    method: "GET",
    originalUrl: "https://api.example.test/v1/orders",
    defaultBaseUrl: "https://api.example.test",
    hostname: "api.example.test",
    path: "/v1/orders",
    pathPattern: "/v1/orders",
    pathWithQuery: "/v1/orders",
    query: {},
    requestHeaders: {},
    responseStatus: 200,
    responseHeaders: {
      "content-type": "application/json",
    },
    responseContentType: "application/json",
    responseBody: {
      orders: [{ id: "order-1", total: 12 }],
      total: 1,
    },
    responseTimeMs: 60,
    groupName: "api-example-test-v1-orders",
    testName: "GET /v1/orders returns 200",
    schemaName: "get-api-example-test-v1-orders.response.schema.json",
    dynamicSegments: [],
  };
}

function deleteEntry(): NormalizedHarEntry {
  return {
    id: "delete-api-example-test-items-id",
    sourceFile: "delete.har",
    entryIndex: 0,
    method: "DELETE",
    originalUrl: "https://api.example.test/items/42",
    defaultBaseUrl: "https://api.example.test",
    hostname: "api.example.test",
    path: "/items/42",
    pathPattern: "/items/{id}",
    pathWithQuery: "/items/${ITEM_ID}",
    query: {},
    requestHeaders: {},
    responseStatus: 204,
    responseHeaders: {},
    responseTimeMs: 40,
    groupName: "api-example-test-items",
    testName: "DELETE /items/{id} returns 204",
    dynamicSegments: ["42"],
  };
}

function loginEntry(): NormalizedHarEntry {
  return {
    id: "post-api-example-test-auth-main-login",
    sourceFile: "login.har",
    entryIndex: 0,
    method: "POST",
    originalUrl: "https://api.example.test/auth/main/login",
    defaultBaseUrl: "https://api.example.test",
    hostname: "api.example.test",
    path: "/auth/main/login",
    pathPattern: "/auth/main/login",
    pathWithQuery: "/auth/main/login",
    query: {},
    requestHeaders: {
      authorization: "${API_AUTHORIZATION}",
      "content-type": "application/json",
    },
    requestBody: {
      _csrf: "${CSRF_TOKEN}",
      email: "${TEST_EMAIL}",
      password: "${TEST_PASSWORD}",
    },
    requestMimeType: "application/json",
    responseStatus: 200,
    responseHeaders: {
      "content-type": "application/json",
    },
    responseContentType: "application/json",
    responseBody: {
      ok: true,
    },
    responseTimeMs: 100,
    groupName: "api-example-test-auth",
    testName: "POST /auth/main/login returns 200",
    fixtureName: "post-api-example-test-auth-main-login.request.json",
    schemaName: "post-api-example-test-auth-main-login.response.schema.json",
    dynamicSegments: [],
  };
}
