#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';

import { listSpecFiles, parseSpecHeader, specSha256 } from './lib/spec-parser.mjs';
import { isPendingGenerationSpec, validateSpecFile } from './validate-flow-spec.mjs';

function driftStatus(testPath, specPath) {
  if (!fs.existsSync(testPath)) {
    return 'missing test';
  }

  const header = parseSpecHeader(fs.readFileSync(testPath, 'utf8'));
  if (!header) {
    return 'no header';
  }

  if (header.specPath !== specPath) {
    return 'header spec mismatch';
  }

  return header.sha256 === specSha256(specPath) ? 'no' : 'yes';
}

// Deterministic "covered/total" NEG coverage: a spec NEG-### id counts as
// covered when the target test file mentions it. Pending or missing tests
// report zero coverage without changing the deterministic output shape.
function negCoverage(validation, testPath) {
  const negIds = (validation.negativeCases ?? []).map((negative) => negative.caseId);
  if (negIds.length === 0) {
    return 'none';
  }

  if (!testPath || !fs.existsSync(testPath)) {
    return `0/${negIds.length}`;
  }

  const content = fs.readFileSync(testPath, 'utf8');
  const covered = negIds.filter((negId) => content.includes(negId)).length;
  return `${covered}/${negIds.length}`;
}

function writeCatalog(specDir = 'specs', outputPath = 'docs/ai-testing/coverage.md') {
  const rows = [];

  for (const specPath of listSpecFiles(specDir)) {
    const validation = validateSpecFile(specPath);
    const metadata = validation.metadata;
    const testPath = metadata['Target Test File'] ?? '';
    rows.push({
      flowId: metadata['Flow ID'] ?? 'invalid',
      owner: metadata.Owner ?? 'unassigned',
      testPath,
      acIds: validation.acceptanceCriteria.join(', '),
      dataCases: validation.dataCases?.none ? 'none' : String(validation.dataCases?.rows?.length ?? 0),
      jsonDataCases: Array.isArray(validation.dataCasesJson) ? String(validation.dataCasesJson.length) : 'invalid',
      businessRules: validation.businessRules?.none ? 'none' : String(validation.businessRules?.rows?.length ?? 0),
      negCoverage: negCoverage(validation, testPath),
      drift: isPendingGenerationSpec(metadata)
        ? 'pending-generation'
        : testPath
          ? driftStatus(testPath, specPath)
          : 'missing test',
      specVersion: metadata['Spec Version'] ?? 'unknown'
    });
  }

  const content = [
    '# AI Testing Coverage Catalog',
    '',
    'Generated by `npm run ai:spec:catalog`. Do not edit manually.',
    '',
    '| Flow ID | Owner | Spec Version | Test File | AC IDs | Data Cases | JSON Data Cases | Business Rules | NEG Coverage | Drift? |',
    '|---|---|---|---|---|---:|---:|---:|---|---|',
    ...rows.map(
      (row) =>
        `| ${row.flowId} | ${row.owner} | ${row.specVersion} | ${row.testPath} | ${row.acIds} | ${row.dataCases} | ${row.jsonDataCases} | ${row.businessRules} | ${row.negCoverage} | ${row.drift} |`
    ),
    ''
  ].join('\n');

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);
  console.log(`Spec catalog written to ${outputPath}`);
}

function printHelp() {
  console.log(`Usage:
  node scripts/ai/spec-catalog.mjs [--dir specs] [--out docs/ai-testing/coverage.md]

Writes a generated coverage catalog for flow specs.`);
}

function runCli() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    printHelp();
    return;
  }

  const dirIndex = args.indexOf('--dir');
  const outIndex = args.indexOf('--out');
  const specDir = dirIndex >= 0 ? args[dirIndex + 1] : 'specs';
  const outputPath = outIndex >= 0 ? args[outIndex + 1] : 'docs/ai-testing/coverage.md';

  if (!specDir || !outputPath) {
    printHelp();
    process.exit(1);
  }

  writeCatalog(specDir, outputPath);
}

runCli();
