import path from 'node:path';
import { compareStrings } from '../utils/compare.js';
import type { HarApiTestConfig } from '../types/config.js';
import type { SupportedHttpMethod } from '../types/har.js';
import type { JsonValue } from '../types/json.js';
import type {
  ExpectedStatus,
  GeneratedEndpointTestCase,
  GeneratedScenarioTestCase,
  GeneratedTestPlan,
  GeneratedTestStep,
  MutationRisk,
  TestCategory,
  TestExecution
} from '../types/testCase.js';
import { writeJsonFile, writeTextFile } from '../utils/fileSystem.js';
import { slugify } from '../utils/url.js';
import { generateJsonSchemaFromSamples } from './schemaGenerator.js';
import { buildPlaywrightAuthSetupFile, buildPlaywrightSupportFile } from './playwrightSupport.js';

export interface GeneratedOutputContext {
  parsedEntries?: number;
  filteredEntries?: number;
  sourceHarFiles?: string[];
}

const generatedFileBanner =
  '// GENERATED by har-api-tests — do not edit by hand.\n' +
  '// Regenerate with: npm run generate -- --har <your capture file or folder>\n';

function withGeneratedBanner(content: string): string {
  return `${generatedFileBanner}\n${content}`;
}

export async function writeGeneratedTests(
  plan: GeneratedTestPlan,
  outDir: string,
  config: HarApiTestConfig,
  context: GeneratedOutputContext = {}
): Promise<string[]> {
  const generatedFiles: string[] = [];
  let schemaCount = 0;
  const supportPath = path.join(outDir, config.output.supportDir, 'apiTestUtils.ts');
  const authSetupPath = path.join(outDir, config.output.supportDir, 'authSetup.ts');
  await writeTextFile(supportPath, withGeneratedBanner(buildPlaywrightSupportFile(collectHosts(plan))));
  await writeTextFile(authSetupPath, withGeneratedBanner(buildPlaywrightAuthSetupFile()));
  generatedFiles.push(supportPath, authSetupPath);

  for (const [fixtureName, payload] of collectFixtures(plan)) {
    const fixturePath = path.join(outDir, config.output.fixturesDir, fixtureName);
    await writeJsonFile(fixturePath, payload);
    generatedFiles.push(fixturePath);
  }

  const schemaSamples = collectSchemaSamples(plan.endpointCases);
  for (const testCase of plan.endpointCases) {
    if (!testCase.schemaName || testCase.responseBody === undefined || !testCase.assertSchema) {
      continue;
    }

    const schemaPath = path.join(outDir, config.output.schemasDir, testCase.schemaName);
    const samples = schemaSamples.get(schemaGroupKey(testCase)) ?? [testCase.responseBody];
    await writeJsonFile(schemaPath, generateJsonSchemaFromSamples(samples, testCase.title));
    generatedFiles.push(schemaPath);
    schemaCount += 1;
  }

  for (const [fileKey, testCases] of groupEndpointCases(plan.endpointCases)) {
    const specPath = path.join(outDir, `${fileKey}.spec.ts`);
    await writeTextFile(specPath, withGeneratedBanner(buildEndpointSpecFile(fileKey, testCases, config)));
    generatedFiles.push(specPath);
  }

  for (const scenario of plan.scenarioCases) {
    const specPath = path.join(outDir, 'scenarios', scenario.fileName);
    await writeTextFile(specPath, withGeneratedBanner(buildScenarioSpecFile(scenario, config)));
    generatedFiles.push(specPath);
  }

  const runManifestPath = path.join(outDir, 'run-manifest.json');
  const envExamplePath = path.join(outDir, '.env.generated.example');
  const environment = collectEnvironmentUsage(plan);

  if (environment.required.length > 0) {
    // "00-" sorts ahead of every endpoint spec, so with workers=1 the env check runs first.
    const preflightPath = path.join(outDir, '00-preflight.spec.ts');
    await writeTextFile(preflightPath, withGeneratedBanner(buildPreflightSpecFile(environment.required, config)));
    generatedFiles.push(preflightPath);
  }
  await writeJsonFile(runManifestPath, buildRunManifest(plan, context, environment, schemaCount));
  await writeTextFile(envExamplePath, buildEnvExample(environment));
  generatedFiles.push(runManifestPath, envExamplePath);

  // Per-route status manifest for the deterministic replay mock (scripts/replay-mock-server.mjs).
  // Lets the blanket-200 mock become status-aware so a capture whose ACTIVE @smoke tier includes a
  // non-200 status (e.g. a 201 create) is still satisfied without a live system-under-test.
  const replayManifestPath = path.join(outDir, 'replay-manifest.json');
  await writeJsonFile(replayManifestPath, buildReplayManifest(plan));
  generatedFiles.push(replayManifestPath);

  return generatedFiles.sort();
}

interface ReplayRoute {
  method: SupportedHttpMethod;
  pathPattern: string;
  hostname: string;
  status: number;
  // Observed response content type — active smokes assert `toContain(<base type>)`, so the mock
  // must answer text/html routes with text/html, not a blanket application/json.
  contentType: string;
}

// Mirrors the mock's pattern matching so generation-time collision checks see what the mock sees.
function replayPatternToRegExp(pathPattern: string): RegExp {
  const source = pathPattern
    .split(/\{[^}]+\}/)
    .map((literal) => literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('[^/]+');
  return new RegExp(`^${source}$`);
}

// The active @smoke tier is exactly what `npm run test:api:replay` runs against the mock. Emit each
// active-smoke route's exact expected status + content type so the mock can answer it; family-status
// (non-exact) cases never reach the mock (they are test.fixme / excluded by --grep @smoke), and
// scenario/CRUD specs carry no @smoke tag so the replay grep never runs them — both omitted.
function buildReplayManifest(plan: GeneratedTestPlan): { routes: ReplayRoute[] } {
  const routes: ReplayRoute[] = [];
  for (const testCase of plan.endpointCases) {
    if (testCase.category !== 'smoke' || testCase.execution !== 'active') {
      continue;
    }
    if (testCase.expectedStatus.kind !== 'exact') {
      continue;
    }
    routes.push({
      method: testCase.method,
      pathPattern: testCase.pathPattern,
      hostname: testCase.hostname,
      status: testCase.expectedStatus.status,
      contentType: testCase.responseContentType ?? 'application/json'
    });
  }

  // The replay mock matches on method+path only and takes the first match (literal routes before
  // pattern routes). Two collision shapes are surfaced at generation time so ambiguity is visible
  // instead of silently serving the wrong status:
  //  1. exact same method+pathPattern on different hosts with different statuses;
  //  2. a {param} pattern route whose regex also matches a same-method LITERAL sibling route
  //     (literal wins at the mock now, but the overlap deserves a look if statuses differ).
  const firstByKey = new Map<string, ReplayRoute>();
  for (const route of routes) {
    const key = `${route.method} ${route.pathPattern}`;
    const first = firstByKey.get(key);
    if (!first) {
      firstByKey.set(key, route);
    } else if (first.status !== route.status) {
      console.warn(
        `[har-api-tests] replay-manifest route collision: "${key}" expects ${first.status} on ${first.hostname} ` +
          `but ${route.status} on ${route.hostname}. The replay mock matches method+path only and will serve the ` +
          `first (${first.status}); disambiguate by host or path if both statuses matter.`
      );
    }
  }
  const patternRoutes = routes.filter((route) => route.pathPattern.includes('{'));
  const literalRoutes = routes.filter((route) => !route.pathPattern.includes('{'));
  for (const pattern of patternRoutes) {
    const regex = replayPatternToRegExp(pattern.pathPattern);
    for (const literal of literalRoutes) {
      if (literal.method === pattern.method && regex.test(literal.pathPattern) && literal.status !== pattern.status) {
        console.warn(
          `[har-api-tests] replay-manifest pattern/literal overlap: "${pattern.method} ${pattern.pathPattern}" ` +
            `(${pattern.status}) also matches literal "${literal.pathPattern}" (${literal.status}). The mock matches ` +
            `literal routes first, so the literal wins for that exact path.`
        );
      }
    }
  }

  return { routes };
}

export interface SupportHostInfo {
  primaryHost: string;
  knownHosts: string[];
}

function collectHosts(plan: GeneratedTestPlan): SupportHostInfo {
  const counts = new Map<string, number>();
  for (const testCase of plan.endpointCases) {
    counts.set(testCase.hostname, (counts.get(testCase.hostname) ?? 0) + 1);
  }
  for (const scenario of plan.scenarioCases) {
    for (const step of scenario.steps) {
      const host = hostnameFromBaseUrl(step.defaultBaseUrl);
      if (host) {
        counts.set(host, (counts.get(host) ?? 0) + 1);
      }
    }
  }

  const ranked = [...counts.entries()].sort((left, right) => right[1] - left[1] || compareStrings(left[0], right[0]));
  return {
    primaryHost: ranked[0]?.[0] ?? '',
    knownHosts: ranked.map(([host]) => host).sort()
  };
}

function hostnameFromBaseUrl(baseUrl: string): string | undefined {
  try {
    return new URL(baseUrl).hostname;
  } catch {
    return undefined;
  }
}

function collectFixtures(plan: GeneratedTestPlan): Map<string, unknown> {
  const fixtures = new Map<string, unknown>();

  for (const testCase of plan.endpointCases) {
    if (testCase.fixtureName && testCase.requestBody !== undefined) {
      fixtures.set(testCase.fixtureName, testCase.requestBody);
    }
  }

  for (const scenario of plan.scenarioCases) {
    for (const step of scenario.steps) {
      if (step.fixtureName && step.requestBody !== undefined) {
        fixtures.set(step.fixtureName, step.requestBody);
      }
    }
  }

  return new Map([...fixtures.entries()].sort(([left], [right]) => compareStrings(left, right)));
}

function collectSchemaSamples(cases: GeneratedEndpointTestCase[]): Map<string, JsonValue[]> {
  const samples = new Map<string, JsonValue[]>();

  for (const testCase of cases) {
    if (testCase.responseBody === undefined || !testCase.assertSchema) {
      continue;
    }

    const key = schemaGroupKey(testCase);
    samples.set(key, [...(samples.get(key) ?? []), testCase.responseBody]);
  }

  return samples;
}

function schemaGroupKey(testCase: GeneratedEndpointTestCase): string {
  return `${testCase.hostname}:${testCase.method}:${testCase.pathPattern}:${expectedStatusLiteral(testCase.expectedStatus)}`;
}

function groupEndpointCases(cases: GeneratedEndpointTestCase[]): Map<string, GeneratedEndpointTestCase[]> {
  const groups = new Map<string, GeneratedEndpointTestCase[]>();

  for (const testCase of cases) {
    const key = `${slugify(testCase.hostname)}/${slugify(testCase.pathPattern)}`;
    groups.set(key, [...(groups.get(key) ?? []), testCase]);
  }

  return new Map(
    [...groups.entries()]
      .map(([key, values]): [string, GeneratedEndpointTestCase[]] => [
        key,
        values.sort((left, right) => compareStrings(`${left.category} ${left.title}`, `${right.category} ${right.title}`))
      ])
      .sort(([left], [right]) => compareStrings(left, right))
  );
}

interface SpecImportUsage {
  expect: boolean;
  fixtures: boolean;
  inferredTest: boolean;
  schema: boolean;
  sensitiveFields: boolean;
}

function endpointSpecUsage(testCases: GeneratedEndpointTestCase[]): SpecImportUsage {
  return {
    expect: testCases.some((testCase) => testCase.assertContentType && Boolean(testCase.responseContentType)),
    fixtures: testCases.some((testCase) => Boolean(testCase.fixtureName)),
    inferredTest: testCases.some(isCalibrationCandidate),
    schema: testCases.some((testCase) => Boolean(testCase.schemaName) && testCase.assertSchema),
    sensitiveFields: testCases.some((testCase) => testCase.assertNoSensitiveFields)
  };
}

function scenarioSpecUsage(scenario: GeneratedScenarioTestCase): SpecImportUsage {
  return {
    expect: scenario.steps.some((step) => Boolean(step.responseContentType)),
    fixtures: scenario.steps.some((step) => Boolean(step.fixtureName)),
    inferredTest: false,
    schema: false,
    sensitiveFields: false
  };
}

function buildPlaywrightImport(usage: SpecImportUsage): string {
  return usage.expect ? "import { test, expect } from '@playwright/test';" : "import { test } from '@playwright/test';";
}

function buildSupportImport(importPrefix: string, supportDir: string, usage: SpecImportUsage): string {
  const imports = ['assertResponseTime', 'assertStatusCode', 'sendApiRequest'];

  if (usage.sensitiveFields) {
    imports.unshift('assertNoSensitiveFieldsInJsonResponse');
  }

  if (usage.inferredTest) {
    imports.splice(imports.indexOf('sendApiRequest'), 0, 'inferredTest');
  }

  // Schema assertions load the schema JSON via loadJsonFromTestFile even when no fixture exists
  // (e.g. a GET endpoint with a JSON response body and no request body).
  if (usage.fixtures || usage.schema) {
    imports.push('loadJsonFromTestFile');
  }

  if (usage.fixtures) {
    imports.push('resolvePayload');
  }

  if (usage.schema) {
    imports.push('readJsonResponse', 'validateSchema');
  }

  return `import {
${imports.map((name) => `  ${name}`).join(',\n')}
} from '${importPrefix}/${supportDir}/apiTestUtils.js';`;
}

function buildEndpointSpecFile(
  fileKey: string,
  testCases: GeneratedEndpointTestCase[],
  config: HarApiTestConfig
): string {
  const hostDepth = fileKey.split('/').length - 1;
  const importPrefix = hostDepth === 0 ? '.' : '..';
  const assetPrefix = hostDepth === 0 ? './' : '../';
  const tests = testCases.map((testCase) => buildEndpointTestCase(testCase, config, assetPrefix)).join('\n');
  const suiteName = `${testCases[0]?.hostname ?? 'generated'} ${testCases[0]?.pathPattern ?? fileKey}`;
  const usage = endpointSpecUsage(testCases);

  return `${buildPlaywrightImport(usage)}
${buildSupportImport(importPrefix, config.output.supportDir, usage)}

test.describe('${escapeSingleQuoted(suiteName)}', () => {
${tests}});
`;
}

function buildScenarioSpecFile(scenario: GeneratedScenarioTestCase, config: HarApiTestConfig): string {
  const usage = scenarioSpecUsage(scenario);
  const names = ['test'];
  if (usage.expect) {
    names.push('expect');
  }
  if (scenario.isolated) {
    // Isolated scenarios create their own APIRequestContext via the module-level `request`.
    names.push('request');
  }
  const playwrightImport = `import { ${names.join(', ')} } from '@playwright/test';`;

  return `${playwrightImport}
${buildSupportImport('..', config.output.supportDir, usage)}

test.describe('scenarios', () => {
${buildScenarioTestCase(scenario, config)}});
`;
}

function buildEndpointTestCase(
  testCase: GeneratedEndpointTestCase,
  config: HarApiTestConfig,
  assetPrefix: string
): string {
  // Calibration candidates use the support module's inferredTest so CALIBRATION_MODE can flip
  // every unverified bad-input=>4xx expectation to active in one run.
  const runner = isCalibrationCandidate(testCase) ? 'inferredTest' : testRunner(testCase.execution);
  const requestOptions = buildSendApiRequestOptions(testCase, 'requestBody');
  const contentTypeAssertion =
    testCase.assertContentType && testCase.responseContentType
      ? `    expect(response.headers()['content-type'] ?? '').toContain('${escapeSingleQuoted(baseContentType(testCase.responseContentType))}');\n`
      : '';
  const schemaAssertion =
    testCase.schemaName && testCase.assertSchema
      ? `    const responseBody = await readJsonResponse(response, '${escapeSingleQuoted(testCase.title)}');\n    const schema = loadJsonFromTestFile<object>(testInfo.file, '${assetPrefix}${config.output.schemasDir}/${testCase.schemaName}');\n    validateSchema(responseBody, schema, '${escapeSingleQuoted(testCase.title)}');\n`
      : '';
  const noSensitiveAssertion = testCase.assertNoSensitiveFields
    ? `    await assertNoSensitiveFieldsInJsonResponse(response, '${escapeSingleQuoted(testCase.title)}');\n`
    : '';
  const title = taggedEndpointTitle(testCase);
  const calibrationNote = testCase.calibration ? ` | calibration: ${testCase.calibration}` : '';

  return `  // origin: ${testCase.origin} | category: ${testCase.category} | confidence: ${testCase.confidence} | execution: ${testCase.execution} | mutationRisk: ${testCase.mutationRisk}${calibrationNote}
  ${runner}('${escapeSingleQuoted(title)}', async ({ request }, testInfo) => {
${testCase.fixtureName ? `    const requestBody = resolvePayload(loadJsonFromTestFile<unknown>(testInfo.file, '${assetPrefix}${config.output.fixturesDir}/${testCase.fixtureName}'));\n` : ''}    const { response, elapsedMs } = await sendApiRequest(${requestOptions});

    assertStatusCode(response.status(), ${expectedStatusLiteral(testCase.expectedStatus)}, '${escapeSingleQuoted(testCase.title)}', '${escapeSingleQuoted(testCase.hostname)}');
${contentTypeAssertion}    assertResponseTime(elapsedMs, ${testCase.responseTimeBudgetMs});
${schemaAssertion}${noSensitiveAssertion}  });

`;
}

function buildScenarioTestCase(scenario: GeneratedScenarioTestCase, config: HarApiTestConfig): string {
  const runner = testRunner(scenario.execution);
  const title = taggedScenarioTitle(scenario);
  const contextExpr = scenario.isolated ? 'sessionContext' : 'request';
  const steps = scenario.steps
    .map((step, index) => buildScenarioStep(step, config, index + 1, contextExpr, scenario.isolated))
    .join('\n');
  const comment = `  // origin: ${scenario.origin} | category: ${scenario.category} | confidence: ${scenario.confidence} | execution: ${scenario.execution} | mutationRisk: ${scenario.mutationRisk} | isolated: ${scenario.isolated}`;

  if (scenario.isolated) {
    // Run the flow in its own request context so its login/logout only affect its own session.
    const indentedSteps = steps
      .split('\n')
      .map((line) => (line ? `  ${line}` : line))
      .join('\n');
    return `${comment}
  ${runner}('${escapeSingleQuoted(title)}', async ({}, testInfo) => {
    const sessionContext = await request.newContext({ ignoreHTTPSErrors: true });
    try {
${indentedSteps}    } finally {
      await sessionContext.dispose();
    }
  });

`;
  }

  return `${comment}
  ${runner}('${escapeSingleQuoted(title)}', async ({ request }, testInfo) => {
${steps}  });

`;
}

function taggedEndpointTitle(testCase: GeneratedEndpointTestCase): string {
  const tags = [testCase.category === 'smoke' ? '@smoke' : '@extended', ...serviceTagsForPath(testCase.pathPattern)];
  if (testCase.mutationRisk !== 'none') {
    tags.push('@mutating');
  }
  if (isCalibrationCandidate(testCase)) {
    tags.push('@calibrate');
  }
  return `${testCase.title} ${tags.join(' ')}`;
}

function taggedScenarioTitle(scenario: GeneratedScenarioTestCase): string {
  const serviceTags = uniqueTags(scenario.steps.flatMap((step) => serviceTagsForPath(step.pathWithQuery)));
  const tags = ['@extended', ...serviceTags];
  if (scenario.mutationRisk !== 'none') {
    tags.push('@mutating');
  }
  return `${scenario.title} ${tags.join(' ')}`;
}

function isCalibrationCandidate(testCase: GeneratedEndpointTestCase): boolean {
  return (testCase.category === 'negative' || testCase.category === 'security') && testCase.execution === 'fixme';
}

function serviceTagsForPath(pathLike: string): string[] {
  const segments = pathLike
    .split('?')[0]
    .split('/')
    .map((segment) => segment.toLowerCase())
    .filter((segment) => segment && !segment.startsWith('{') && !segment.startsWith('${') && !/^v\d+$/.test(segment));

  if (segments.length === 0) {
    return ['@api'];
  }

  if (segments[0] === 'auth' || segments.some((segment) => ['login', 'logout', 'oauth', 'password', 'session', 'token'].includes(segment))) {
    return ['@auth'];
  }

  if (
    ['me', 'user', 'users'].includes(segments[0]) ||
    segments.some((segment) =>
      ['account', 'activity', 'notifications', 'preferences', 'security', 'support', 'talk-settings', 'twostepauthsettings'].includes(segment)
    )
  ) {
    return ['@profile'];
  }

  return [`@${slugify(segments[0])}`];
}

function uniqueTags(tags: string[]): string[] {
  return [...new Set(tags)].sort();
}

function buildPreflightSpecFile(requiredEnvNames: string[], config: HarApiTestConfig): string {
  const namesLiteral = `[${[...requiredEnvNames].sort().map((name) => `'${escapeSingleQuoted(name)}'`).join(', ')}]`;

  return `import { expect, test } from '@playwright/test';
import { resolveGeneratedEnvValue } from './${config.output.supportDir}/apiTestUtils.js';

const requiredEnvNames = ${namesLiteral};

test('preflight: required environment variables are resolvable @smoke @preflight', () => {
  const missing = requiredEnvNames.filter((name) => {
    try {
      resolveGeneratedEnvValue(name);
      return false;
    } catch {
      return true;
    }
  });

  expect(
    missing,
    'Missing required environment variables: ' +
      missing.join(', ') +
      '. Fill them in (copy tests/generated/.env.generated.example to .env) before running the generated suite.'
  ).toEqual([]);
});
`;
}

function buildScenarioStep(
  step: GeneratedTestStep,
  config: HarApiTestConfig,
  stepNumber: number,
  contextExpr: string,
  isolated: boolean
): string {
  const requestOptions = buildSendApiRequestOptions(step, `step${stepNumber}Body`, contextExpr, isolated);
  const contentTypeAssertion = step.responseContentType
    ? `    expect(step${stepNumber}Response.headers()['content-type'] ?? '').toContain('${escapeSingleQuoted(baseContentType(step.responseContentType))}');\n`
    : '';

  return `${step.fixtureName ? `    const step${stepNumber}Body = resolvePayload(loadJsonFromTestFile<unknown>(testInfo.file, '../${config.output.fixturesDir}/${step.fixtureName}'));\n` : ''}    const { response: step${stepNumber}Response, elapsedMs: step${stepNumber}ElapsedMs } = await sendApiRequest(${requestOptions});
    assertStatusCode(step${stepNumber}Response.status(), ${expectedStatusLiteral(step.expectedStatus)}, '${escapeSingleQuoted(step.label)}');
${contentTypeAssertion}    assertResponseTime(step${stepNumber}ElapsedMs, ${step.responseTimeBudgetMs});
`;
}

function buildSendApiRequestOptions(
  step: GeneratedTestStep,
  payloadVariable: string,
  contextExpr = 'request',
  isolated = false
): string {
  const options: string[] = [
    contextExpr === 'request' ? 'request' : `request: ${contextExpr}`,
    `defaultBaseUrl: '${escapeSingleQuoted(step.defaultBaseUrl)}'`,
    `path: '${escapeSingleQuoted(step.pathWithQuery)}'`,
    `method: '${step.method}'`
  ];
  if (isolated) {
    options.push('isolatedSession: true');
  }
  if (Object.keys(step.requestHeaders).length > 0) {
    options.push(`headers: ${JSON.stringify(step.requestHeaders, null, 2)}`);
  }

  if (step.fixtureName) {
    options.push(`payload: ${payloadVariable}`);
  }

  return `{\n${options.map((option) => indent(option, 6)).join(',\n')}\n    }`;
}

interface EnvironmentVariableManifest {
  name: string;
  required: boolean;
  usedIn: string[];
}

interface EnvironmentUsage {
  required: string[];
  optional: string[];
  variables: EnvironmentVariableManifest[];
}

const authSetupEnvironment = [
  'AUTH_BASE_URL',
  'AUTH_BEARER_HOSTS',
  'AUTH_COOKIE_DOMAIN',
  'AUTH_COOKIE_HOST',
  'AUTH_CSRF_HEADER',
  'AUTH_CSRF_JSON_PATH',
  'AUTH_CSRF_SOURCE_PATH',
  'AUTH_LOGIN_BODY',
  'AUTH_LOGIN_CONTENT_TYPE',
  'AUTH_LOGIN_HEADERS',
  'AUTH_LOGIN_METHOD',
  'AUTH_LOGIN_PATH',
  'AUTH_LOGIN_URL',
  'AUTH_SETUP_ENABLED'
];

function collectEnvironmentUsage(plan: GeneratedTestPlan): EnvironmentUsage {
  const required = new Set<string>(['TEST_EMAIL', 'TEST_PASSWORD']);
  const optional = new Set<string>(['API_COOKIE', 'BASE_URL', ...authSetupEnvironment]);
  const usedIn = new Map<string, Set<string>>([
    ['API_COOKIE', new Set(['auth login setup'])],
    ['BASE_URL', new Set(['base URL override'])],
    ['TEST_EMAIL', new Set(['auth login setup'])],
    ['TEST_PASSWORD', new Set(['auth login setup'])]
  ]);

  for (const envName of authSetupEnvironment) {
    usedIn.set(envName, new Set(['auth login setup']));
  }

  for (const testCase of plan.endpointCases) {
    collectStepEnvironmentUsage(testCase, testCase.title, required, optional, usedIn);
  }

  for (const scenario of plan.scenarioCases) {
    for (const [index, step] of scenario.steps.entries()) {
      collectStepEnvironmentUsage(step, `${scenario.title} step ${index + 1}: ${step.label}`, required, optional, usedIn);
    }
  }

  const requiredNames = [...required].sort();
  const optionalNames = [...optional].filter((name) => !required.has(name)).sort();
  const variables = [...new Set([...requiredNames, ...optionalNames])]
    .sort()
    .map((name) => ({
      name,
      required: required.has(name),
      usedIn: [...(usedIn.get(name) ?? [])].sort()
    }));

  return {
    required: requiredNames,
    optional: optionalNames,
    variables
  };
}

function collectStepEnvironmentUsage(
  step: GeneratedTestStep,
  label: string,
  required: Set<string>,
  optional: Set<string>,
  usedIn: Map<string, Set<string>>
): void {
  collectPlaceholders(step.pathWithQuery, 'required', `${label} path`, required, optional, usedIn);

  for (const [headerName, value] of Object.entries(step.requestHeaders)) {
    collectPlaceholders(value, 'optional', `${label} header ${headerName}`, required, optional, usedIn);
  }

  collectPayloadPlaceholders(step.requestBody, `${label} payload`, required, optional, usedIn);
}

function collectPayloadPlaceholders(
  value: unknown,
  label: string,
  required: Set<string>,
  optional: Set<string>,
  usedIn: Map<string, Set<string>>
): void {
  if (typeof value === 'string') {
    collectPlaceholders(value, 'required', label, required, optional, usedIn);
    return;
  }

  if (Array.isArray(value)) {
    value.forEach((item, index) => collectPayloadPlaceholders(item, `${label}[${index}]`, required, optional, usedIn));
    return;
  }

  if (value && typeof value === 'object') {
    for (const [key, childValue] of Object.entries(value)) {
      collectPayloadPlaceholders(childValue, `${label}.${key}`, required, optional, usedIn);
    }
  }
}

function collectPlaceholders(
  value: string,
  mode: 'required' | 'optional',
  location: string,
  required: Set<string>,
  optional: Set<string>,
  usedIn: Map<string, Set<string>>
): void {
  for (const envName of placeholderNames(value)) {
    const resolvedMode = envName === 'CACHE_BUSTER' || envName === 'CSRF_TOKEN' ? 'optional' : mode;
    if (resolvedMode === 'required') {
      required.add(envName);
      optional.delete(envName);
    } else if (!required.has(envName)) {
      optional.add(envName);
    }

    usedIn.set(envName, new Set([...(usedIn.get(envName) ?? []), location]));
  }
}

function placeholderNames(value: string): string[] {
  return [...value.matchAll(/\$\{([A-Z0-9_]+)\}/g)].map((match) => match[1]);
}

function buildRunManifest(
  plan: GeneratedTestPlan,
  context: GeneratedOutputContext,
  environment: EnvironmentUsage,
  schemaCount: number
): object {
  const categories: Record<TestCategory, number> = {
    smoke: 0,
    negative: 0,
    security: 0,
    crud: 0,
    scenario: 0
  };
  const executions: Record<TestExecution, number> = {
    active: 0,
    fixme: 0,
    skip: 0
  };
  const mutationRisks: Record<MutationRisk, number> = {
    none: 0,
    guarded: 0,
    unsafe: 0
  };

  for (const testCase of plan.endpointCases) {
    categories[testCase.category] += 1;
    executions[testCase.execution] += 1;
    mutationRisks[testCase.mutationRisk] += 1;
  }

  for (const scenario of plan.scenarioCases) {
    categories[scenario.category] += 1;
    executions[scenario.execution] += 1;
    mutationRisks[scenario.mutationRisk] += 1;
  }

  const smokeCases = plan.endpointCases.filter((testCase) => testCase.category === 'smoke');
  const smokeWithBody = smokeCases.filter((testCase) => testCase.responseBody !== undefined).length;

  return {
    generatedBy: 'har-api-tests',
    sources: {
      harFiles: [...(context.sourceHarFiles ?? [])].map((file) => path.relative(process.cwd(), file)).sort(),
      parsedEntries: context.parsedEntries ?? null,
      filteredEntries: context.filteredEntries ?? null
    },
    summary: {
      totalTests: plan.endpointCases.length + plan.scenarioCases.length,
      endpointTests: plan.endpointCases.length,
      scenarioTests: plan.scenarioCases.length,
      schemaCount,
      schemaCoverage: schemaCoverageLabel(smokeCases.length, smokeWithBody),
      smokeEndpoints: smokeCases.length,
      smokeEndpointsWithResponseBody: smokeWithBody,
      categories,
      executions,
      mutationRisks
    },
    environment
  };
}

function schemaCoverageLabel(smokeCount: number, smokeWithBody: number): 'none' | 'partial' | 'full' {
  if (smokeCount === 0 || smokeWithBody === 0) {
    return 'none';
  }

  return smokeWithBody === smokeCount ? 'full' : 'partial';
}

function buildEnvExample(environment: EnvironmentUsage): string {
  const requiredLines = environment.required.map((name) => `${name}=`);
  const optionalLines = environment.optional.map((name) => `${name}=${defaultEnvExampleValue(name)}`);

  return [
    '# Required generated test variables',
    ...(requiredLines.length > 0 ? requiredLines : ['# none']),
    '',
    '# Optional generated test variables',
    ...(optionalLines.length > 0 ? optionalLines : ['# none'])
  ].join('\n');
}

function defaultEnvExampleValue(name: string): string {
  if (name === 'AUTH_CSRF_HEADER') {
    return 'x-csrf-token';
  }

  if (name === 'AUTH_CSRF_SOURCE_PATH') {
    return '/user/session';
  }

  if (name === 'AUTH_LOGIN_CONTENT_TYPE') {
    return 'application/json';
  }

  if (name === 'AUTH_LOGIN_HEADERS') {
    return '{}';
  }

  if (name === 'AUTH_LOGIN_METHOD') {
    return 'POST';
  }

  if (name === 'AUTH_LOGIN_PATH') {
    return '/auth/main/login';
  }

  if (name === 'AUTH_SETUP_ENABLED') {
    return 'true';
  }

  if (name === 'CACHE_BUSTER') {
    return '1';
  }

  return '';
}

function expectedStatusLiteral(expectedStatus: ExpectedStatus): string {
  return JSON.stringify(expectedStatus);
}

function testRunner(execution: TestExecution): string {
  if (execution === 'fixme') {
    return 'test.fixme';
  }

  if (execution === 'skip') {
    return 'test.skip';
  }

  return 'test';
}

function baseContentType(contentType: string): string {
  return contentType.split(';')[0].trim();
}

function escapeSingleQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function indent(value: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return value
    .split('\n')
    .map((line) => `${prefix}${line}`)
    .join('\n');
}
